services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entryPoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=elliott@zenful.cloud"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      # - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build: .
    labels:
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`)"
    ports:
      - 127.0.0.1:3000:3000
    environment:
      SQLITE_DATA: /data
      IS_PROD: 0
    volumes:
      - db-data:/data
volumes:
  db-data:
